# Configuración para Java directamente, con certificado de un nombre DNS válido.
server:
  address: 0.0.0.0
  port: 8443
  ssl:
    enabled: true
    key-store: ${TLS_KEY_STORE}
    key-store-password: ${TLS_KEY_STORE_PASSWORD}
    key-store-type: PKCS12
