-- Preserve movement kind and manual classification metadata.
UPDATE movement SET category = 'NO_COMPUTABLE', subcategory = CASE kind WHEN 'CARD_SETTLEMENT' THEN 'LIQUIDACION_TARJETA' WHEN 'WALLET_SETTLEMENT' THEN 'LIQUIDACION_PAYPAL' WHEN 'INTERNAL_TRANSFER' THEN 'TRASPASO_INTERNO' WHEN 'DUPLICATE' THEN 'MOVIMIENTO_DUPLICADO' END
WHERE kind IN ('CARD_SETTLEMENT', 'WALLET_SETTLEMENT', 'INTERNAL_TRANSFER', 'DUPLICATE');

UPDATE classification_rule SET category = 'NO_COMPUTABLE', subcategory = CASE kind WHEN 'CARD_SETTLEMENT' THEN 'LIQUIDACION_TARJETA' WHEN 'WALLET_SETTLEMENT' THEN 'LIQUIDACION_PAYPAL' WHEN 'INTERNAL_TRANSFER' THEN 'TRASPASO_INTERNO' WHEN 'DUPLICATE' THEN 'MOVIMIENTO_DUPLICADO' END
WHERE kind IN ('CARD_SETTLEMENT', 'WALLET_SETTLEMENT', 'INTERNAL_TRANSFER', 'DUPLICATE');

