CREATE TABLE category (
  id BIGINT NOT NULL AUTO_INCREMENT,
  code VARCHAR(64) NOT NULL,
  name VARCHAR(100) NOT NULL,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  display_order INT NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  CONSTRAINT uk_category_code UNIQUE (code)
);

CREATE TABLE subcategory (
  id BIGINT NOT NULL AUTO_INCREMENT,
  category_id BIGINT NOT NULL,
  code VARCHAR(64) NOT NULL,
  name VARCHAR(100) NOT NULL,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  display_order INT NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  CONSTRAINT uk_subcategory_category_code UNIQUE (category_id, code),
  CONSTRAINT fk_subcategory_category FOREIGN KEY (category_id) REFERENCES category(id)
);

INSERT INTO category (code, name, display_order) VALUES
('INGRESOS','Ingresos',10),('VIVIENDA','Vivienda',20),('ALIMENTACION','Alimentación',30),
('TRANSPORTE','Transporte',40),('OCIO','Ocio',50),('SALUD','Salud',60),('EDUCACION','Educación',70),
('SEGUROS','Seguros',80),('COMPRAS','Compras',90),('SUSCRIPCIONES','Suscripciones',100),
('IMPUESTOS','Impuestos',110),('TRANSFERENCIAS','Transferencias',120),('EFECTIVO','Efectivo',130),('OTROS','Otros',140);

INSERT INTO subcategory (category_id, code, name, display_order)
SELECT c.id, s.code, s.name, s.display_order
FROM category c
JOIN (
 SELECT 'INGRESOS' category_code,'NOMINA' code,'Nómina' name,10 display_order UNION ALL
 SELECT 'INGRESOS','DEVOLUCIONES','Devoluciones',20 UNION ALL SELECT 'INGRESOS','OTROS_INGRESOS','Otros ingresos',30 UNION ALL
 SELECT 'VIVIENDA','HIPOTECA_ALQUILER','Hipoteca / alquiler',10 UNION ALL SELECT 'VIVIENDA','HIPOTECA','Hipoteca',20 UNION ALL
 SELECT 'VIVIENDA','ELECTRICIDAD','Electricidad',30 UNION ALL SELECT 'VIVIENDA','GAS','Gas',40 UNION ALL SELECT 'VIVIENDA','AGUA','Agua',50 UNION ALL
 SELECT 'VIVIENDA','INTERNET','Internet',60 UNION ALL SELECT 'VIVIENDA','COMUNIDAD','Comunidad',70 UNION ALL
 SELECT 'ALIMENTACION','SUPERMERCADO','Supermercado',10 UNION ALL SELECT 'ALIMENTACION','RESTAURANTES','Restaurantes',20 UNION ALL SELECT 'ALIMENTACION','COMIDA_DOMICILIO','Comida a domicilio',30 UNION ALL
 SELECT 'TRANSPORTE','COMBUSTIBLE','Combustible',10 UNION ALL SELECT 'TRANSPORTE','TRANSPORTE_PUBLICO','Transporte público',20 UNION ALL
 SELECT 'TRANSPORTE','APARCAMIENTO','Aparcamiento',30 UNION ALL SELECT 'TRANSPORTE','PEAJES','Peajes',40 UNION ALL
 SELECT 'TRANSPORTE','MANTENIMIENTO_COCHE','Mantenimiento coche',50 UNION ALL SELECT 'TRANSPORTE','FINANCIACION_VEHICULO','Financiación vehículo',60 UNION ALL
 SELECT 'OCIO','VIAJES','Viajes',10 UNION ALL SELECT 'OCIO','CINE_TEATRO','Cine / teatro',20 UNION ALL SELECT 'OCIO','DEPORTE','Deporte',30 UNION ALL SELECT 'OCIO','OTROS_OCIO','Otros ocio',40 UNION ALL
 SELECT 'SALUD','FARMACIA','Farmacia',10 UNION ALL SELECT 'SALUD','MEDICO','Médico',20 UNION ALL SELECT 'SALUD','DENTISTA','Dentista',30 UNION ALL SELECT 'SALUD','OTROS_SALUD','Otros salud',40 UNION ALL
 SELECT 'EDUCACION','COLEGIO_UNIVERSIDAD','Colegio / universidad',10 UNION ALL SELECT 'EDUCACION','CURSOS','Cursos',20 UNION ALL SELECT 'EDUCACION','LIBROS_MATERIAL','Libros / material',30 UNION ALL
 SELECT 'SEGUROS','HOGAR','Hogar',10 UNION ALL SELECT 'SEGUROS','AUTO','Auto',20 UNION ALL SELECT 'SEGUROS','SALUD','Salud',30 UNION ALL SELECT 'SEGUROS','VIDA','Vida',40 UNION ALL SELECT 'SEGUROS','OTROS_SEGUROS','Otros seguros',50 UNION ALL
 SELECT 'COMPRAS','ONLINE','Online',10 UNION ALL SELECT 'COMPRAS','ROPA','Ropa',20 UNION ALL SELECT 'COMPRAS','HOGAR','Hogar',30 UNION ALL SELECT 'COMPRAS','TECNOLOGIA','Tecnología',40 UNION ALL SELECT 'COMPRAS','OTRAS_COMPRAS','Otras compras',50 UNION ALL
 SELECT 'SUSCRIPCIONES','STREAMING','Streaming',10 UNION ALL SELECT 'SUSCRIPCIONES','SOFTWARE','Software',20 UNION ALL SELECT 'SUSCRIPCIONES','TELEFONIA','Telefonía',30 UNION ALL SELECT 'SUSCRIPCIONES','OTRAS_SUSCRIPCIONES','Otras suscripciones',40 UNION ALL
 SELECT 'IMPUESTOS','HACIENDA','Hacienda',10 UNION ALL SELECT 'IMPUESTOS','TASAS','Tasas',20 UNION ALL SELECT 'IMPUESTOS','MULTAS','Multas',30 UNION ALL
 SELECT 'TRANSFERENCIAS','TRASPASO_INTERNO','Traspaso interno',10 UNION ALL SELECT 'TRANSFERENCIAS','LIQUIDACION_TARJETA','Liquidación tarjeta',20 UNION ALL
 SELECT 'TRANSFERENCIAS','LIQUIDACION_PAYPAL','Liquidación PayPal',30 UNION ALL SELECT 'TRANSFERENCIAS','LIQUIDACION_MONEDERO','Liquidación monedero',40 UNION ALL SELECT 'TRANSFERENCIAS','TRANSFERENCIA_EXTERNA','Transferencia externa',50 UNION ALL
 SELECT 'EFECTIVO','RETIRADA_CAJERO','Retirada cajero',10 UNION ALL SELECT 'OTROS','OTROS','Otros',10
) s ON s.category_code = c.code;
