import{useEffect,useState}from'react';
import{CalendarDays,CreditCard,Landmark,LayoutDashboard,Lightbulb,PiggyBank,ReceiptText,RefreshCw,Search,TrendingDown,TrendingUp,TriangleAlert,Wallet}from'lucide-react';
import{Bar,BarChart,CartesianGrid,Cell,Pie,PieChart,ResponsiveContainer,Tooltip,XAxis,YAxis}from'recharts';
import{api,CategoryStat,Insight,Movement,Overview,Product,TrendPoint}from'./api';

const eur=(n:number)=>new Intl.NumberFormat('es-ES',{style:'currency',currency:'EUR'}).format(Number(n||0));
const dateLabel=(d:string)=>new Intl.DateTimeFormat('es-ES',{day:'2-digit',month:'short'}).format(new Date(d+'T00:00:00'));
function Card({title,value,sub,icon:Icon,tone='blue'}:{title:string;value:string;sub:string;icon:any;tone?:string}){return <div className="card kpi"><div className={'icon '+tone}><Icon size={21}/></div><div><span className="muted">{title}</span><strong>{value}</strong><small>{sub}</small></div></div>}
function Title({t}:{t:string}){return <div className="title"><h2>{t}</h2></div>}
function Empty({children}:{children:string}){return <div className="empty">{children}</div>}

export default function App(){
 const[now]=useState(new Date()),[overview,setOverview]=useState<Overview|null>(null),[trend,setTrend]=useState<TrendPoint[]>([]),[categories,setCategories]=useState<CategoryStat[]>([]),[products,setProducts]=useState<Product[]>([]),[movements,setMovements]=useState<Movement[]>([]),[insights,setInsights]=useState<Insight[]>([]),[forecast,setForecast]=useState<any>(null),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const from=new Date(now.getFullYear(),now.getMonth(),1).toISOString().slice(0,10),to=now.toISOString().slice(0,10);
 useEffect(()=>{let active=true;setLoading(true);setError('');Promise.all([api.overview(from,to),api.trend(from,to,undefined,'DAY'),api.categories(from,to),api.products(),api.movements(from,to,undefined,10),api.insights(from,to),api.forecast(from,to)]).then(([o,t,c,p,m,i,f])=>{if(!active)return;setOverview(o);setTrend(t);setCategories(c);setProducts(p);setMovements(m);setInsights(i);setForecast(f)}).catch(e=>{if(active)setError(e instanceof Error?e.message:'No se pudo cargar el dashboard')}).finally(()=>active&&setLoading(false));return()=>{active=false}},[from,to]);
 const projected=Number(forecast?.projectedExpenses??forecast?.expenses??0);
 return <div className="shell"><aside><div className="brand"><b>▥</b><span>Finance Suite</span></div><nav><a className="active"><LayoutDashboard/>Inicio</a><a><TrendingUp/>Evolución</a><a><ReceiptText/>Gastos</a><a><CreditCard/>Productos</a><a><Search/>Movimientos</a><a><RefreshCw/>Recurrentes</a><a><CalendarDays/>Calendario</a><a><Lightbulb/>Insights</a><a><TriangleAlert/>Revisar</a></nav><div className="version"><span className={error?'dot':'dot live'}></span>{loading?'Cargando API':error?'API no disponible':'API conectada'}<small>v0.5.0</small></div></aside>
 <main><header><div><h1>Resumen financiero</h1><p>Tu situación financiera de un vistazo</p></div><div className="period">Este mes · {from} — {to}</div></header>
 {error&&<div className="api-error"><b>No se han podido cargar los datos.</b><span>{error}</span></div>}
 {loading?<div className="loading">Cargando información financiera…</div>:overview&&<>
 <section className="kpis"><Card title="Saldo total" value={eur(overview.totalBalance)} sub="Disponible en cuentas y monederos" icon={Wallet} tone="green"/><Card title="Ingresos del mes" value={eur(overview.income)} sub="Movimientos contabilizados" icon={TrendingUp}/><Card title="Gastos del mes" value={eur(overview.expenses)} sub={eur(overview.averageDailyExpense)+' / día'} icon={TrendingDown} tone="red"/><Card title="Ahorro del mes" value={eur(overview.savings)} sub={Number(overview.savingsRate).toFixed(1)+' % tasa de ahorro'} icon={PiggyBank} tone="purple"/></section>
 <section className="grid3"><div className="card wide"><Title t="Evolución financiera"/>{trend.length?<ResponsiveContainer width="100%" height={245}><BarChart data={trend}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="date" tickFormatter={dateLabel}/><YAxis/><Tooltip labelFormatter={(v)=>dateLabel(String(v))} formatter={(v)=>eur(Number(v))}/><Bar dataKey="income" name="Ingresos" fill="#42c997" radius={[5,5,0,0]}/><Bar dataKey="expenses" name="Gastos" fill="#ff7474" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer>:<Empty>Sin movimientos en el período.</Empty>}</div>
 <div className="card"><Title t="Gastos por categoría"/>{categories.length?<div className="pie"><ResponsiveContainer width="48%" height={220}><PieChart><Pie data={categories} dataKey="amount" nameKey="category" innerRadius={55} outerRadius={82}>{categories.map((_,i)=><Cell key={i}/>)}</Pie><Tooltip formatter={(v)=>eur(Number(v))}/></PieChart></ResponsiveContainer><div className="legend">{categories.slice(0,7).map(c=><div key={c.category}><span>{c.category}</span><b>{eur(c.amount)}</b></div>)}</div></div>:<Empty>Sin gastos clasificados.</Empty>}</div>
 <div className="card forecast"><Title t="Previsión"/>{projected>0?<><strong>{eur(projected)}</strong><p>Proyección calculada por el servidor para los próximos 30 días.</p></>:<Empty>El servidor no dispone de una proyección para este período.</Empty>}</div></section>
 <section className="bottom"><div className="card"><Title t="Movimientos recientes"/>{movements.length?<div className="rows">{movements.slice(0,5).map(m=><div className="row" key={m.id}><span>{dateLabel(m.date)}</span><b>{m.merchant||m.description}</b><em className={Number(m.amount)>0?'pos':'neg'}>{eur(m.amount)}</em><small>{m.category||'Sin categoría'}</small></div>)}</div>:<Empty>Sin movimientos recientes.</Empty>}</div>
 <div className="card"><Title t="Financial Insights"/>{insights.length?insights.map(i=><div key={i.code} className={'insight '+(i.severity==='POSITIVE'?'good':i.severity==='WARNING'?'warn':'')}><b>{i.title}</b><br/>{i.detail}</div>):<Empty>No hay insights para este período.</Empty>}</div>
 <div className="card"><Title t="Productos financieros"/>{products.length?products.slice(0,5).map(p=><div className="product" key={p.id}><Landmark/><span><b>{p.name}</b><small>{p.provider} · {p.type}{p.maskedPan?' · '+p.maskedPan:''}</small></span><strong>{eur(p.balance)}</strong></div>):<Empty>No hay productos registrados.</Empty>}</div></section></>}</main></div>
}